name: "Daily AI News"

on:
  schedule:
    # Run daily at 18:00 UTC
    - cron: '0 18 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  daily-ai-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Archive old AI Generated Posts
      id: archive_posts
      run: node .github/scripts/archive_posts.js
      env:
        MAX_POSTS: 30
        
    - name: Draft Daily AI News
      id: draft-news
      run: node .github/scripts/ai-draft-news.js
      env:
        LANGDOCK_API_KEY: ${{ secrets.LANGDOCK_API_KEY }}
        TOPIC: "KI"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/debug/
        git add _drafts/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add daily AI news drafts"
          git push
        fi 
      
    - name: Sync archiv posts and assets to sharaal/archiv repository
      run: |
        # Clone the target repository
        git clone https://${{ secrets.GH_PAT }}@github.com/sharaal/archiv.git target-repo

        # Copy archived posts to target repository
        cp -r _archives/* target-repo/_posts/
        mkdir -p target-repo/assets
        cp -r assets/* target-repo/assets/
        
        # Commit and push changes to target repository
        cd target-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _posts/
        git add assets/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Sync archived posts and assets from main repository"
          git push
        fi
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
